language: node_js
matrix:
  include:
    - node_js: "node"
sudo: required
dist: trusty
before_script:
  - mkdir -p vendors
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.40.zip -nv
  - unzip -qd vendors google_appengine_1.9.40.zip
  - ./vendors/google_appengine/dev_appserver.py --skip_sdk_update_check --port=8090 . &
  - npm install -g lighthouse
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - npm explore -g lighthouse -- ./lighthouse-core/scripts/download-chrome.sh
  - mv $(npm root -g)/lighthouse/chrome-linux .
  - $LIGHTHOUSE_CHROMIUM_PATH --version
  - npm run build
script:
  - lighthouse --output=json http://localhost:8090/devsummit --output-path=./validate/log.json
  - node ./validate/checklog.js ./validate/log.json
